function Hd = ff
%FF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 27-Nov-2018 00:30:36

% Elliptic Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are normalized to 1.

N      = 2;     % Order
Fpass1 = 0.1;   % First Passband Frequency
Fpass2 = 0.14;  % Second Passband Frequency
Apass  = 1;     % Passband Ripple (dB)
Astop  = 80;    % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandstop('N,Fp1,Fp2,Ap,Ast', N, Fpass1, Fpass2, Apass, Astop);
Hd = design(h, 'ellip');

% [EOF]
