function Hd = GaussF
%GAUSSF Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 30-Oct-2018 19:46:28

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are normalized to 1.

N     = 10;       % Order
Fc    = 0.12;     % Cutoff Frequency
flag  = 'scale';  % Sampling Flag
Alpha = 2.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = gausswin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc, 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
