function Hd = iir_order10
%IIR_ORDER10 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 11-Dec-2018 23:41:41

% Butterworth Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are normalized to 1.

N   = 10;   % Order
Fc1 = 0.1;  % First Cutoff Frequency
Fc2 = 0.2;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandstop('N,F3dB1,F3dB2', N, Fc1, Fc2);
Hd = design(h, 'butter');

% [EOF]
