function Hd = noisy1bandstoporder10
%NOISY1BANDSTOPORDER10 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 11-Nov-2018 16:03:07

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N      = 10;              % Order
Fpass1 = 0.09;            % First Passband Frequency
Fstop1 = 0.12;            % First Stopband Frequency
Fstop2 = 0.15;            % Second Stopband Frequency
Fpass2 = 0.2;             % Second Passband Frequency
Wpass1 = 0.028774368332;  % First Passband Weight
Wstop  = 0.001;           % Stopband Weight
Wpass2 = 0.0575011;       % Second Passband Weight
dens   = 20;              % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 1], [1 1 0 0 1 1], ...
           [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
