function Hd = noisy1bandstoporder98
%NOISY1BANDSTOPORDER98 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 11-Nov-2018 16:15:22

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N      = 98;    % Order
Fpass1 = 0.09;  % First Passband Frequency
Fstop1 = 0.12;  % First Stopband Frequency
Fstop2 = 0.14;  % Second Stopband Frequency
Fpass2 = 0.15;  % Second Passband Frequency
Wpass1 = 1;     % First Passband Weight
Wstop  = 1;     % Stopband Weight
Wpass2 = 1;     % Second Passband Weight
dens   = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 1], [1 1 0 0 1 1], ...
           [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
